config/routes.rb
Ecomme::Application.routes.draw do


  ActiveAdmin.routes(self)
  devise_for :users, :controllers => {:registrations => "registrations"}, 
  :path => '', :path_names => {
    :sign_in => 'login', 
    :sign_out => 'logout', 
    :sign_up => 'join', 
    :edit => 'account/settings'
  }

  resources :users

  resources :line_items do
    member do
      post   'change_quantity_of'
      delete 'change_quantity_of'
    end
  end

  resources :orders

  resources :store

  resources :carts

  resources :products do
    get :customers, on: :member
  end

  root "store#index"


end

app/models/cart.rb
class Cart < ActiveRecord::Base
    has_many :line_items, dependent: :destroy
    belongs_to :user

  def add_product(product_id)
    current_item = line_items.find_by(product_id: product_id)
    if current_item
      current_item.quantity += 1
    else
      current_item = line_items.build(product_id: product_id)
    end
    current_item
  end

  def total_price
    line_items.to_a.sum { |item| item.total_price}
  end

end

app/controllers/carts_controller.rb
class CartsController < ApplicationController

  before_action :set_cart, only: [:show, :edit, :update, :destroy]

  rescue_from ActiveRecord::RecordNotFound, with: :invalid_cart

  # GET /carts
  # GET /carts.json
  def index
    authenticate_user!
    if current_user.admin?
      @carts = Cart.all
    else
      redirect_to root_url, notice: 'Yo-ho-ho'
    end
  end

  # GET /carts/1
  # GET /carts/1.json
  def show
  end

  # GET /carts/new
  def new
    @cart = Cart.new
  end

  # GET /carts/1/edit
  def edit
  end

  # POST /carts
  # POST /carts.json
  def create
    @cart = Cart.new(cart_params)

    respond_to do |format|
      if @cart.save
        format.html { redirect_to @cart, notice: 'Cart was successfully created.' }
        format.json { render :show, status: :created, location: @cart }
      else
        format.html { render :new }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /carts/1
  # PATCH/PUT /carts/1.json
  def update
    respond_to do |format|
      if @cart.update(cart_params)
        format.html { redirect_to @cart, notice: 'Cart was successfully updated.' }
        format.json { render :show, status: :ok, location: @cart }
      else
        format.html { render :edit }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /carts/1
  # DELETE /carts/1.json
  def destroy
    if @cart.id == session[:cart_id]
      @cart.destroy
      session[:cart_id] = nil
    else
      authenticate_admin_user!
      @cart.destroy
    end
    respond_to do |format|
      format.html { redirect_to :back, notice: 'Your cart is empty now' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cart
      @cart = Cart.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cart_params
      params[:cart]
    end
      

    def invalid_cart
      logger.error "Попытка доступа к несуществующей корзине #{params[:id]}"
      redirect_to root_url, notice: "Cart doesn't exist"
    end
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/views/carts/_cart.html.haml
-unless cart.line_items.empty?
  %h5 Cart
  %ul.list-group
    = render partial: 'line_items/line_item', collection: cart.line_items
  / - @cart.line_items.each do |item|
  /  %li.line-item
  /    = item.quantity
  /    \× 
  /    = link_to item.product.title, store_path(item.product)
  /    = number_to_currency(item.total_price)
  /    = button_to item, method: :delete, class:'btn btn-xs btn-danger' do
  /      .glyphicon.glyphicon-trash
  %h4= "Total: #{number_to_currency(cart.total_price)}"


  -unless current_page?(new_order_path)
    = button_to "Delete cart", cart, method: :delete, data:{confirm: 'Sure?'}, class: 'btn btn-danger btn-xs'
    = button_to "Checkout", new_order_path, method: :get, class: 'btn btn-success btn-xs'

app/views/carts/_form.html.haml
= simple_form_for(@cart) do |f|
  = f.error_notification

  .form-inputs

  .form-actions
    = f.button :submit

app/views/carts/edit.html.haml
%h1 Editing cart

= render 'form'

= link_to 'Show', @cart
\|
= link_to 'Back', carts_path

app/views/carts/index.html.haml
%h1 Listing carts

%table
  %tr
    %th
    %th
    %th

  - @carts.each do |cart|
    %tr
      %td= link_to 'Show', cart
      %td= link_to 'Edit', edit_cart_path(cart)
      %td= link_to 'Destroy', cart, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Cart', new_cart_path

app/views/carts/new.html.haml
%h1 New cart

= render 'form'

= link_to 'Back', carts_path

app/views/carts/show.html.haml
= render @cart