config/routes.rb
Ecomme::Application.routes.draw do


  ActiveAdmin.routes(self)
  devise_for :users, :controllers => {:registrations => "registrations"}, 
  :path => '', :path_names => {
    :sign_in => 'login', 
    :sign_out => 'logout', 
    :sign_up => 'join', 
    :edit => 'account/settings'
  }

  resources :users

  resources :line_items do
    member do
      post   'change_quantity_of'
      delete 'change_quantity_of'
    end
  end

  resources :orders

  resources :store

  resources :carts

  resources :products do
    get :customers, on: :member
  end

  root "store#index"


end

app/models/line_item.rb
class LineItem < ActiveRecord::Base
  belongs_to :order
  belongs_to :product
  belongs_to :cart

  #Count total price of LineItem
  def total_price
    product.price * quantity
  end

  #Decrease line_item quantity by 1, when 0 - destroy
  def decrease!
    self.quantity > 1 ? self.quantity -= 1 : self.destroy
    self
  end

  #Increase line_item quantity by 1.
  def increase!
    self.quantity += 1
    self
  end
end

app/controllers/line_items_controller.rb
class LineItemsController < ApplicationController
  include CurrentCart
  before_action :set_cart, only: [:create, :destroy, :change_quantity_of]
  before_action :set_line_item, only: [:show, :edit, :update, :destroy]

  # GET /line_items
  # GET /line_items.json
  def index
    @line_items = LineItem.all
  end

  # GET /line_items/1
  # GET /line_items/1.json
  def show
  end

  # GET /line_items/new
  def new
    @line_item = LineItem.new
  end

  # GET /line_items/1/edit
  def edit
  end

  # POST /line_items
  # POST /line_items.json
  def create
    @cart = current_cart
    product = Product.find(params[:product_id])
    @line_item = @cart.add_product(product.id)

    respond_to do |format|
      if @line_item.save
        format.html { redirect_to :back, notice: "Item was added to your cart" }
        format.js   { @current_item = @line_item}
        format.json { render :show, status: :created, location: @line_item }
      else
        format.html { render :new }
        format.json { render json: @line_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /line_items/1
  # PATCH/PUT /line_items/1.json
  def update
    respond_to do |format|
      if @line_item.update(line_item_params)
        format.html { redirect_to @line_item, notice: 'Line item was successfully updated.' }
        format.json { render :show, status: :ok, location: @line_item }
      else
        format.html { render :edit }
        format.json { render json: @line_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /line_items/1
  # DELETE /line_items/1.json
  def destroy
    @line_item = LineItem.find(params[:id])
    @line_item.destroy
    respond_to do |format|
      if current_cart.line_items.empty?
        format.html {redirect_to :back, notice: 'Your cart is empty'}
        format.js {@current_item = @line_item}
      else
        format.html {redirect_to :back, notice: 'Item removed!'}
        format.js {@current_item = @line_item}
      end
    end
  end

  # POST/DELETE line_items/1
  #Depends on http method, specified in view "line_items/_line_item.html.haml".  
  def change_quantity_of
    @line_item = @cart.line_items.find_by_id(params[:id])
    request.delete? ? @line_item.decrease! : @line_item.increase!
    respond_to do |format|
      if @line_item.save
        format.html {redirect_to :back, notice: 'Quantity has been successfully changed'}
        format.js {@current_item = @line_item}
        format.json {head :ok}
      else
        format.html {redirect_to :back, notice: 'Something went wrong. Try again'}
        format.js {@current_item = @line_item}
        format.json {head :ok}
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_line_item
      @line_item = LineItem.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def line_item_params
      params.require(:line_item).permit(:product_id)
    end
end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/views/line_items/_form.html.haml
= simple_form_for(@line_item) do |f|
  = f.error_notification

  .form-inputs
    = f.association :product
    = f.association :cart

  .form-actions
    = f.button :submit

app/views/line_items/_line_item.html.haml
%li.list-group-item.line-item{id: line_item==@current_item ? 'current_item' : ''}
  %ul.list-unstyled
    %li
      = line_item.quantity 
      \× 
      = link_to line_item.product.title, store_path(line_item.product)
    %li= number_to_currency(line_item.total_price)
    %li.btn-group
      = button_to line_item, method: :delete, remote: true, class:'btn btn-danger btn-xs' do
        .glyphicon.glyphicon-trash   
      = button_to change_quantity_of_line_item_path(line_item), method: :post, remote: true, class:'btn btn-success btn-xs' do
        .glyphicon.glyphicon-plus   
      = button_to change_quantity_of_line_item_path(line_item), method: :delete, remote: true, class:'btn btn-success btn-xs' do
        .glyphicon.glyphicon-minus

app/views/line_items/_line_item_mail.html.haml
%div
  = line_item.quantity 
  \× 
  %br/
  = link_to line_item.product.title, store_path(line_item.product)
  %br/
  = number_to_currency(line_item.total_price)

app/views/line_items/change_quantity_of.js.haml
$('#cart').html("#{escape_javascript render(@cart)}");

$('#current_item').css({'background-color':'yellow'}).animate({'background-color':'#fff'}, 1000);

app/views/line_items/create.js.haml
$('#cart').html("#{escape_javascript render(@cart)}");

$('#current_item').css({'background-color':'yellow'}).animate({'background-color':'#fff'}, 1000);

app/views/line_items/decrease.js.haml
$('#cart').html("#{escape_javascript render(@cart)}");

$('#current_item').css({'background-color':'yellow'}).animate({'background-color':'#fff'}, 1000);

app/views/line_items/destroy.js.haml
$('#cart').html("#{escape_javascript render(@cart)}");

$('#current_item').css({'background-color':'yellow'}).animate({'background-color':'#fff'}, 1000);

app/views/line_items/edit.html.haml
%h1 Editing line_item

= render 'form'

= link_to 'Show', @line_item
\|
= link_to 'Back', line_items_path

app/views/line_items/index.html.haml
%h1 Listing line_items

%table
  %tr
    %th Product
    %th Cart
    %th
    %th
    %th

  - @line_items.each do |line_item|
    %tr
      %td= line_item.product
      %td= line_item.cart
      %td= link_to 'Show', line_item
      %td= link_to 'Edit', edit_line_item_path(line_item)
      %td= link_to 'Destroy', line_item, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Line item', new_line_item_path

app/views/line_items/new.html.haml
%h1 New line_item

= render 'form'

= link_to 'Back', line_items_path

app/views/line_items/show.html.haml
%p
  %b Product:
  = @line_item.product
%p
  %b Cart:
  = @line_item.cart

= link_to 'Edit', edit_line_item_path(@line_item)
\|
= link_to 'Back', line_items_path